/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 * Simple program to display the current date and time using the Real Time Clock (RTC) module
 *
 ******************************************************************************
 */

// Includes
#include "main.h"
#include "usart.h"
#include "gpio.h"
#include "rtc.h"

// Defines
// LSE
#define PWR_CLK_EN	(1UL << 28)
#define DBP_SET		(1UL << 8)
#define LSE_ON		(1UL << 0)
#define LSE_RDY		(1UL << 1)

// SysTick
#define CLK_SRC_INT 		(1UL << 2)
#define SYSTICK_EN 			(1UL << 0)
#define SYSTICK_CNT_SET 	(1UL << 16)

// HSE
#define CLK_HSEON			(1UL << 16)
#define CLK_HSERDY			(1UL << 17)
#define CLK_CSS_ON			(1UL << 19)

// Globals
uint32_t sys_freq = 16000000;
char err_message[2000] = {'\0'};
int lse_on = 0;
int hse_on = 0;

// Function declarations
void lse_init(void);
void hse_init_set(void);

// Main
int main(void)
{
	// Initialize LSE and HSE and set HSE as system clock
	hse_init_set();
	lse_init();

	// Initializations
	usart2_init();

	// Check clock source status
	printf("\033[0;0H");
	printf("\033[2J");
	if(lse_on) printf("LSE STATUS : ON\r\n");
	if(hse_on)
	{
		printf("HSE STATUS : ON \r\n");
		printf("Clock Freq : %lu \r\n", sys_freq);
	}

	while(1)
	{

	}

	return 0;
}

// Select the external 8 MHz clock as system clock
void hse_init_set(void)
{
	// Enable external clock
	RCC->CR |= CLK_HSEON;

	// Wait till external clock is ready
	while(!(RCC->CR & CLK_HSERDY));

	// Enable clock security system (might be important for external clock src)
	RCC->CR |= CLK_CSS_ON;

	// Switch to external clock using the RCC CFGR reg)
	RCC->CFGR |= (1UL << 0);
	RCC->CFGR &= ~(1UL << 1);

	// Check if external clock is being used. Set the value of sys_freq accordingly
	if((RCC->CFGR & (1UL << 2)) && (!(RCC->CFGR & (1UL << 3))))
	{
		hse_on = 1;
		sys_freq = 8000000;
	}

}

// Enable low speed external oscillator as clock source for RTC
void lse_init(void)
{
	// Provide clock access to PWR Control
	RCC->APB1ENR |= PWR_CLK_EN;

	// Set the DBP (disable backup domain write protection) bit in the Power Control Register to enable write in
	// Backup Domain control register to enable LSE
	PWR->CR |= DBP_SET;

	// Enable LSE using the RCC Backup Domain Control register
	RCC->BDCR |= LSE_ON;

	// Check if LSE is ready
	if(RCC->BDCR & LSE_RDY) lse_on = 1;
}

// Systick delay in ms
void delay_ms(int ms)
{
	SysTick->LOAD = ((sys_freq / 1000000) * 1000) - 1;	// Gives us update event 1000 times a sec so once each ms
	SysTick->VAL = 0;	// Set the current value register to 0
	SysTick->CTRL |= CLK_SRC_INT;
	SysTick->CTRL |= SYSTICK_EN;

	for(int i = 0; i < ms; i++)
	{
		// Wait until count flag is set
		while(!(SysTick->CTRL & SYSTICK_CNT_SET));
		SysTick->CTRL &= ~(SYSTICK_CNT_SET);
	}
}
