/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 * Simple program to generate morse code depending on the message
 ******************************************************************************
 */

// Includes
#include "main.h"
#include "gpio.h"
#include "usart.h"
#include "morse.h"

// Defines
#define CLK_SRC_INT 		(1UL << 2)
#define SYSTICK_EN 			(1UL << 0)
#define SYSTICK_CNT_SET 	(1UL << 16)
#define CLK_HSEON			(1UL << 16)
#define CLK_HSERDY			(1UL << 17)
#define CLK_CSS_ON			(1UL << 19)
#define TIM2_CLK_EN			(1UL << 0)
#define TIM2_CEN			(1UL << 0)
#define TIM2_UIE			(1UL << 0)
#define TIM2_UIF			(1UL << 0)

// Globals
uint32_t sys_freq = 16000000;
char err_message[2000] = {'\0'};
char clock_src[100];

// Function declarations (private)
void delay_ms(int ms);
void clk_sel_ext(void);
void led_blink_IT(void);
void error_handler(void);

// Main function
int main(void)
{
	// Use the external 8 MHz clock
	strcpy(clock_src,"Internal");
	clk_sel_ext();

	// Init
	usr_led_gpio_init();
	usart2_init();
	morse_init(500);

	led_blink_IT();

	// Print basic info
	printf("Clock src : %s \r\nClock freq : %lu\r\n", clock_src, sys_freq);
	while(1)
	{
		/*
		printf("Hello world %d \r\n", i++);
		GPIOA->ODR ^= (1UL << 5);
		delay_ms(2000);*/

		// Keep executing morse
		//if(morse_run() == -1) error_handler();
		morse_run();
		delay_ms(5000);
	}
}

// Select the external 8 MHz clock
void clk_sel_ext(void)
{
	// Enable external clock
	RCC->CR |= CLK_HSEON;

	// Wait till external clock is ready
	while(!(RCC->CR & CLK_HSERDY));

	// Enable clock security system (might be important for external clock src)
	RCC->CR |= CLK_CSS_ON;

	// Switch to external clock using the RCC CFGR reg)
	RCC->CFGR |= (1UL << 0);
	RCC->CFGR &= ~(1UL << 1);

	strcpy(clock_src, "External");
	sys_freq = 8000000;

	// Check if external clock is being used. Set the value of sys_freq accordingly
	if((RCC->CFGR & (1UL << 2)) && (!(RCC->CFGR & (1UL << 3))))
	{
		strcpy(clock_src, "External");
		sys_freq = 8000000;
	}

}

// Delay in ms
void delay_ms(int ms)
{
	SysTick->LOAD = ((sys_freq / 1000000) * 1000) - 1;	// Gives us update event 1000 times a sec so once each ms
	SysTick->VAL = 0;	// Set the current value register to 0
	SysTick->CTRL |= CLK_SRC_INT;
	SysTick->CTRL |= SYSTICK_EN;

	for(int i = 0; i < ms; i++)
	{
		// Wait until count flag is set
		while(!(SysTick->CTRL & SYSTICK_CNT_SET));
		SysTick->CTRL &= ~(SYSTICK_CNT_SET);
	}
}

// Error handler
void error_handler(void)
{
	while(1)
	{
		printf("Error : %s\r\n", err_message);
		delay_ms(1000);
	}
}

// Blink LED using timer interrupts (looks cool)
void led_blink_IT(void)
{
	// Disable all interrupts globally
	__disable_irq();

	// Enable clock access to TIM2
	RCC->APB1ENR |= TIM2_CLK_EN;

	// Set the pre-scaler value appropriately to bring it down to 1 MHz
	TIM2->PSC = (sys_freq / 1000000) - 1;

	// Set the auto-reload register to get an update event every 1 second
	TIM2->ARR = 1000000-1;

	// Enable counter
	TIM2->CR1 |= TIM2_CEN;

	// Enable interrupt generation on update event
	TIM2->DIER |= TIM2_UIE;

	// Enable interrupt request handling in NVIC
	NVIC_EnableIRQ(TIM2_IRQn);

	// Enable all interrupts
	__enable_irq();
}

void TIM2_UE_IT_Callback(void)
{
	// Toggle the LED on and OFF
	GPIOA->ODR ^= (1UL << 5);
}

// Interrupt request handler for TIM2 update event generation
void TIM2_IRQHandler(void)
{
	// Check if interrupt is due to update event generation -- Check the status register to get the interrupt type
	if(TIM2->SR & TIM2_UIF)
	{
		// Clear the SR bit
		TIM2->SR &= ~(TIM2_UIF);

		// Callback function for UIF
		TIM2_UE_IT_Callback();
	}
}
